name: Build and Upload ESP32 Firmware

on:
  push:
    branches:
      - main

jobs:
  build-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        echo "Adding Arduino CLI to PATH"
        echo "::add-path::$(pwd)/bin"
        arduino-cli config init
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Compile Sketch
      run: arduino-cli compile --fqbn esp32:esp32:esp32 ./path-to-your-sketch.ino

    - name: Upload Firmware
      if: github.event_name == 'push'
      run: arduino-cli upload --fqbn esp32:esp32:esp32 --port /dev/ttyUSB0 ./path-to-your-sketch.ino
