name: Build and Upload ESP32 Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Data to header file conversion
      run: |
        python data2h.py data/index.html main/indexhtml.h
        python data2h.py data/material-design-icons.ttf main/fontttf.h
        python data2h.py data/material-design-icons.woff main/fontwoff.h
        python data2h.py data/material-design-icons.svg main/fontsvg.h
        python data2h.py data/material-design-icons.eot main/fonteot.h
        python data2h.py data/cert.pem main/certpem.h
        python data2h.py data/key.pem main/keypem.h
    
    - name: Initialize submodules
      run: git submodule update --init --recursive

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32s2
        path: 'esp32-s2-hmi-devkit-1/examples/smart-panel'
